deploy-test:
  stage: build
  script:
    - export PORTAINER_API_TOKEN="${PORTAINER_API_TOKEN}"
    - export IO_PASSWORD="${IO_PASSWORD}"
    - ./others/sim-cicd/simci deploy-portainer-stack -f ./others/portainer-stack.yml gitlab-simfeatures $PORTAINER_URL
