-- Shared SQL FtPurgeAll
truncate table ft_actions;
truncate table ft_attributes;
truncate table ft_guided_object;
truncate table ft_list_item;
truncate table ft_list_ordering;
truncate table ft_m2m;
truncate table ft_m2m_child;
truncate table ft_notification;
truncate table ft_o2m_child;
truncate table ft_obj_inline_child;
truncate table ft_obj_inline_parent;
truncate table ft_publications;
truncate table ft_reflexive_many;
truncate table ft_relationship_m2m;
truncate table ft_relationship_o2m;
truncate table ft_rxm_link;
truncate table ft_search;
truncate table ft_search_reference;
truncate table ft_states;
truncate table ft_states_hist;
truncate table ft_tag;
truncate table ft_tagged_object;
truncate table ft_tgo_tag;
delete from m_user where usr_login like 'pwuser_%';
