services:
  simplicite:
    image: registry.simplicite.io/platform:7-alpha
    restart: always
    container_name: ${COMPOSE_PROJECT_NAME}-app
    environment:
      SYSPARAM_USE_IO: "yes"
      SYSPARAM_USE_IO_TESTER: "yes"
      IO_PASSWORD: "${IO_PASSWORD}"
      DEV_MODE: true
      MODULES_IMPORT_SPEC: |
        title: "${COMPOSE_PROJECT_NAME}"
        modules:
          - name: "SimFeatures"
            git: 
              uri: "https://github.com/simplicitesoftware/module-SimFeatures.git"
              branch: "7.0"
            datasets: true
      JACOCO_MODULES: "SimFeatures"
      JACOCO_DESTFILE_APPEND: false
    volumes:
      - jacoco-data:/usr/local/tomcat/webapps/ROOT/WEB-INF/dbdoc/content/jacoco
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.rule=Host(`${COMPOSE_PROJECT_NAME}.sca.simplicite.io`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.tls.certresolver=leresolver"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-app.loadbalancer.server.port=8443"
volumes:
  jacoco-data:
networks:
  proxy:
    name: proxy
    external: true